dist: bionic
os: linux

git:
  depth: 150

env:
  global:
  - CACHE_DIR="$HOME/misc_cache"
  - MINICONDA_DIR="$HOME/miniconda"
  - GATK_PATH="$CACHE_DIR"
  - PYTHONIOENCODING=UTF8
  
  - DOCKER_REGISTRY="quay.io"
  - DOCKER_REPO_PROD="quay.io/broadinstitute/viral-assemble"
  - DOCKER_REPO_DEV="quay.io/broadinstitute/viral-assemble"
  
  - BOTO_CONFIG=/dev/null # bogus value to override config on travis
  - _JAVA_OPTIONS="-Xmx3g" # overrides jvm opts set elsewhere; see: https://stackoverflow.com/questions/28327620/difference-between-java-options-java-tool-options-and-java-opts

cache:
  directories:
    - $HOME/misc_cache
    - $HOME/miniconda
  timeout: 1000

stages:
  - build
  - test

jobs:
  fast_finish: true
  include:

    - language: generic
      stage: build
      env:
        - TRAVIS_JOB=build_docker
        # DOCKER_USER
        - secure: "b7p66b6qjL1eHCbr3v+duObYXJEPBqZg4oHHstYy72lBTE9A5u4/qkLvCU7wwcH8UGnMpcqLVM1x2vGpqCSJ1SEx3+alaLJnR9WlZ98dMDfX+kOgsR9kUhhpLnjs97ahLsFQVhcJ81IolDtHxlv2b6igKJHI4ntZtRW2JaNVuApiPnxycunEA4emBcWLlSm8E6mkUx/e1dmxi+JXWnjUI2CeayI+OLHAFi3WJkowpEZCd/sQ6rHdLwFN/+EABENX0H/nyHdm7G1Sl7IpoUyACZWV51IkrHqH7E/OY5pK0y/SLXKYq21w0VOGKcOMrKsk3TuwT9yg4OZF5ZYZeXUAifxJGx6BZvoqwEpySvMEN+gpPfu+93lPKvYg5q7Hqupv3ER6KSsx1If5DHBRaCsRvFP4s3XBgRrv3tjRKNNWNrf4tem3ybBu03AqWkjMAo2+ixAiGmYHIj/AXibuI14NJbbs/6cto1NgD7hUChT9GyYVZoyGLRlAh9BXh94JU0krV+A4MVSWHpOurWRjcSwkTfvgkFbUoBXL+s0aC24wyZ1N/JDTshsAQ53pArwB99cAy3+7NnkGW44IAc+O20uvND4ANa9lZDECmJOn4K5uIG5EWMs537lpG7ThQgtCsr0O44yHn6XovxA3+jxpa2VpocTg5yjbZ0o1SBVUK2k0K6w="
        # DOCKER_PASS
        - secure: "1LPm6+IV9ji066QlThCKRojalFlN6z1O+oZncgE/V9FQ82x/T+LCdfFyPDPOhVswTYtzh0GCPhKuhpbiQiGTzicY2wIOiu/dAXmTqesCMI/VttNZIl//Q8/3mfcGKewYLx8zhdWd4ihkuumyqK28fcLs4AmZLEqbAlO8hE87lSCjHzj3wMEB0ggMzLM29Cv3GWAcLbQ4+eQcRgfrUSRmUXlf2jwf+C1YQ/PrtB46uRHpX/Gr9Pwi38U7nzLBor/TMvSbCoJ78g/0uuZgbnYg5J5BrWl5n2DLx0EpL2Vf//7wIQGi1+cvX3Uk8uBBb93LdfCADL99pIhSEfMNQ7+0Ux4uWvK/Q+mFP6gclZWbvsi5o1EP24Ra8YQFfV2bIf2KUIspiS/wmmESF2GbOzBLS2H2hQC4l+at2NlaR+CCfXnYvZaQk2UJrWBWb0kMgDzY+avqC6bblM4L7IPyIDgKiMQpwCS4YdROTFmeUFOrWK04ymkUOiDiBrHSG8nHAWHMjNyGFkq6DyBE9FKFkjeS59q/4kDwHLS32esimn46s/a7g31++wiLMKQgqN9fbvXJ11cGecfyT66stukU5GfT1gaALj61LGB46RyeZe/AX9S5o5/2TlHLtgWcjG3huIvccxGJ3HkCnq+thKFErJmyBWwDjomjWcNg1k3+hp3A7PE="
      script:
        - set -e
        - if [ -f "$CACHE_DIR/old-docker-tag.txt" ]; then OLD_DOCKER_TAG=$(cat $CACHE_DIR/old-docker-tag.txt); else OLD_DOCKER_TAG=$DOCKER_REPO_PROD; fi; echo "old docker tag = $OLD_DOCKER_TAG"
        - _CACHE_FROM=""
        - docker pull $OLD_DOCKER_TAG && _CACHE_FROM="--cache-from $OLD_DOCKER_TAG"
        - travis_wait docker build -t local/build-container:build $_CACHE_FROM .
        - travis/deploy-docker.sh
      before_cache:
        - travis/list-docker-tags.sh | tail -1 > $CACHE_DIR/old-docker-tag.txt

    - language: python
      stage: test
      env:
        - TRAVIS_JOB=test_py36_in_docker
        - PYTEST_ADDOPTS="-rsxX -n 2 --durations=25 --fixture-durations=10 --junit-xml=pytest.xml --cov-report= --cov assembly"
      install:
        - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
        - docker pull $DOCKER_TAG
        - travis/install-gatk.sh
        - pip install coveralls==1.1
        - mkdir coverage
      script:
        - docker run -e _JAVA_OPTIONS -e PYTEST_ADDOPTS -v $GATK_PATH:/gatk -v coverage:/coverage --entrypoint /bin/bash $DOCKER_TAG -c 'set -e; cd /opt/viral-ngs/source; gatk3-register /gatk/GenomeAnalysisTK.jar; pytest test/integration test/unit; cp .coverage /coverage'
      after_success:
        - mv coverage/.coverage .
        - coveralls
    
  
